# Introducción a NumPy

La biblioteca Numpy es uno de los caballitos de batalla más utilizados de Python cuando hablamos de cálculo numérico, análisis algebráico y de datos. 

Una de las características principales es que todas las operaciones están vectorizadas.

Antes de poder utilizar las funcionalidades de **NumPy** debemos realizar el *import* correspondiente:

In [4]:
import numpy as np

Definiremos algunos arreglos (*array*) de NumPy y haremos algunos cálculos.

In [54]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])

print(a + b)
print(a * b)
print(a - b)

[ 4  6  8 10]
[ 0  5 12 21]
[-4 -4 -4 -4]


Algunos de los atributos de los *array* de NumPy son:
 - ndarray.ndim: número de dimensiones
 - ndarray.shape: devuelve una tupla con el tamaño del arreglo en cada dimensión
 - ndarray.size: número total de elementos
 - ndarray.dtype: tipos de datos que contiene

In [8]:
x = np.linspace(0,10,21)
y = x**2
print(x)
print(y)

[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10. ]
[   0.      0.25    1.      2.25    4.      6.25    9.     12.25   16.
   20.25   25.     30.25   36.     42.25   49.     56.25   64.     72.25
   81.     90.25  100.  ]


In [9]:
x[13]

6.5

In [10]:
x[0:15]

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ])

In [11]:
x[:8]

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5])

In [12]:
x[-1]

10.0

In [13]:
menor = np.where(x < 4.5)
x[menor]

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [14]:
a = np.array( [[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[1,0]

4

In [49]:
a = np.linspace(0.,10.,11)
print(a)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [50]:
b = a
print b is a
print b

True
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [51]:
b[3] = 25
print a

[  0.   1.   2.  25.   4.   5.   6.   7.   8.   9.  10.]


In [52]:
b = a.copy()
b is a

False

In [53]:
b[3] = 36
print b
print a

[  0.   1.   2.  36.   4.   5.   6.   7.   8.   9.  10.]
[  0.   1.   2.  25.   4.   5.   6.   7.   8.   9.  10.]
